tool: revise aosp_helper
1. simplify the logic
2. extend the usage to non-aosp kernel

diff --git a/tools/script/aosp_helper b/tools/script/aosp_helper
--- a/tools/script/aosp_helper
+++ b/tools/script/aosp_helper
@@ -1,47 +1,62 @@
 #!/usr/bin/env bash
 
-# Assume user has source envsetup.sh already
 # $0 KERNEL_DIR KERNEL_OBJ_DIR
-setup_kernel_cmddb() {
+setup_aosp_kernel_cmddb() {
     local -r build_conf='build.conf'
     local kernel_dir kernel_obj_dir
     local android_dir
     local gen_db_py compile_db
 
-    if [[ -e "$build_conf" ]]; then
-        source $build_conf
-    fi
+    compile_db=compile_commands.json
 
-    kernel_dir="${1:-$kernel_dir}"
-    if [[ ! -e "$kernel_dir" ]]; then
+    # load $kernel_dir
+    [[ -e "$build_conf" ]] && source $build_conf
+
+    kernel_dir=${kernel_dir:-$(readlink -e "$1")}
+    if [[ -z "$kernel_dir" ]]; then
         echo "invalid kernel dir path: $kernel_dir"
         return 128
     fi
-    kernel_dir=$(readlink -e $kernel_dir)
 
-    kernel_obj_dir="$2"
-    if [[ -z "$kernel_obj_dir" ]]; then
-        if [[ -z "$ANDROID_PRODUCT_OUT" ]]; then
-            if [[ -z "$kernel_lunch" ]] || [[ -z "$(declare -F lunch)" ]]; then
-                echo "no lunch config?" >&2
-                return 128
-            fi
-            lunch $kernel_lunch
-        fi
-        kernel_obj_dir=${ANDROID_PRODUCT_OUT}/obj/KERNEL_OBJ
+    if [[ -z "$ANDROID_PRODUCT_OUT" ]]; then
+        . build/envsetup.sh || {
+            echo "no \$ANDROID_PRODUCT_OUT."
+            echo "failed to lunch config."
+            return 2
+        }
+        lunch
+    fi
+    kernel_obj_dir=${ANDROID_PRODUCT_OUT}/obj/KERNEL_OBJ
+
+    setup_kernel_cmddb $kernel_obj_dir
+
+    echo "Link build dir."
+    ln -svf $kernel_obj_dir ${kernel_dir}/build
+
+    echo "copy commands db to $kernel_dir/$compile_db"
+    cp -f ${kernel_obj_dir}/${compile_db} $kernel_dir
+}
+
+setup_kernel_cmddb() {
+    local -r build_conf='build.conf'
+    local kernel_dir
+    local android_dir
+    local gen_db_py compile_db
+
+    compile_db=compile_commands.json
+    gen_db_py=gen_compile_commands.py
+
+    kernel_dir=$(readlink -e "$1")
+    if [[ -z "$kernel_dir" ]]; then
+        echo "invalid kernel dir path: $kernel_dir"
+        return 128
     fi
 
-    cd $kernel_dir
-    echo "linux kernel build out dir: $kernel_obj_dir"
     echo "linux kernel dir: $kernel_dir"
     echo "-------------------------------------------------------------------"
 
-    echo "Link build dir."
-    ln -svf $kernel_obj_dir build
-    cd - &> /dev/null
-
-    gen_db_py=gen_compile_commands.py
-    for dir in "$(pwd)" "$kernel_dir/scripts" "$SHELL_DIR/tools/cmd-db"; do
+    for dir in "$(pwd)" "$kernel_dir/scripts" "$XDG_CONFIG_HOME/toolkit/script"; do
+        echo "search $dir/$gen_db_py..."
         [ -e $dir/$gen_db_py ] && {
             gen_db_py=$dir/$gen_db_py
             break
@@ -49,22 +64,13 @@ setup_kernel_cmddb() {
     done
 
     [ ! -e $gen_db_py ] && {
-        echo "no $gen_db_py to continue" >&2
+        echo "no $gen_db_py to continue"
         return 128
     }
 
-    cp $gen_db_py $kernel_obj_dir
-    gen_db_py=$(basename $gen_db_py)
-
-    compile_db=compile_commands.json
-    cd $kernel_obj_dir
     echo "generate compile commands db..."
-    chmod +x $gen_db_py
-    ./$gen_db_py
 
-    echo "copy commands db to $kernel_dir/$compile_db"
-    cp -f $compile_db $kernel_dir
-    cd - &> /dev/null
+    eval $gen_db_py -d $kernel_dir
 }
 
 # create a cmd_db here
